mongo:
  connectionString: "mongodb://localhost:27017"
  dbname: "emporium"

discord:
  webhook: "https://discord.com/api/webhooks/1283456173667778570/Ds3qwHo5MBe_lym5t2hrexIP5SPZ4XWZluya78QvbxypXs-TmcquIMmb50rjHXsGrc6p"
  bot-name: "Emporium"
  bot-avatar: "https://media.discordapp.net/attachments/1277703220411764819/1283456862062116876/download.jpeg?ex=66e30fd9&is=66e1be59&hm=148e4c43ce1fb9fe29d80007c6bacbf8ecc546dce462454ad9a782742c071c7d&=&format=webp"

  content: "Seller: {seller}"
  embed:
    color: "#Ff0000"
    title: "New sold item"
    fields:
      - name: "Item"
        value: "{item}"
        inline: false
      - name: "Buyer"
        value: "{buyer}"
        inline: false
      - name: "Price"
        value: "{price}"
        inline: false
    description: "Hi!"
    author:
      text: "test"
      url: "https://google.com"
      icon: "https://media.discordapp.net/attachments/1277703220411764819/1283456862062116876/download.jpeg?ex=66e30fd9&is=66e1be59&hm=148e4c43ce1fb9fe29d80007c6bacbf8ecc546dce462454ad9a782742c071c7d&=&format=webp"
    footer:
      text: "wew"
      icon: "https://media.discordapp.net/attachments/1277703220411764819/1283456862062116876/download.jpeg?ex=66e30fd9&is=66e1be59&hm=148e4c43ce1fb9fe29d80007c6bacbf8ecc546dce462454ad9a782742c071c7d&=&format=webp"
